"""create table

Revision ID: b2020fd76c04
Revises: 
Create Date: 2020-07-23 13:51:56.550876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2020fd76c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batchdetails',
    sa.Column('batchid', sa.String(), nullable=False),
    sa.Column('startbatch', sa.String(), nullable=False),
    sa.Column('endbatch', sa.String(), nullable=False),
    sa.Column('cource', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('batchid')
    )
    op.create_table('candidateLogsTbl',
    sa.Column('candidateId', sa.Integer(), nullable=False),
    sa.Column('candidateUsername', sa.String(length=20), nullable=False),
    sa.Column('candidateLogs', sa.String(), nullable=False),
    sa.Column('logtime', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('candidateId')
    )
    op.create_table('customerusertbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customeruserid', sa.String(), nullable=False),
    sa.Column('customerusername', sa.String(), nullable=False),
    sa.Column('customerusertype', sa.String(), nullable=False),
    sa.Column('batchid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enginetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineid', sa.String(), nullable=False),
    sa.Column('enginename', sa.String(), nullable=False),
    sa.Column('enginetype', sa.String(), nullable=False),
    sa.Column('batchid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_status',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('otp_table',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('proctor_batch_detail',
    sa.Column('batch', sa.String(), nullable=False),
    sa.Column('batchname', sa.String(), nullable=False),
    sa.Column('projectid', sa.String(), nullable=False),
    sa.Column('proctorid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('batch')
    )
    op.create_table('tb_customer',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=155), nullable=True),
    sa.Column('created_dt', sa.TIMESTAMP(), server_default=sa.text(u'(now())'), nullable=True),
    sa.Column('deleteflag', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_iframe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iframeid', sa.Integer(), nullable=False),
    sa.Column('iframeurl', sa.String(length=25), nullable=True),
    sa.Column('created_dt', sa.TIMESTAMP(), server_default=sa.text(u'(now())'), nullable=True),
    sa.Column('deleteflag', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iframeid')
    )
    op.create_table('tb_notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=225), nullable=True),
    sa.Column('fromid', sa.String(length=25), nullable=True),
    sa.Column('toid', sa.String(length=25), nullable=True),
    sa.Column('project_code_fk', sa.String(length=25), nullable=True),
    sa.Column('created_dt', sa.TIMESTAMP(), server_default=sa.text(u'(now())'), nullable=True),
    sa.Column('deleteflag', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_project',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=155), nullable=False),
    sa.Column('created_dt', sa.TIMESTAMP(), server_default=sa.text(u'(now())'), nullable=True),
    sa.Column('deleteflag', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('customer_id_fk', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tokenmaster',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('user_detail_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('phoneno', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usermaster',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('candidatedetails',
    sa.Column('useid', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('usercontact', sa.Integer(), nullable=False),
    sa.Column('batchid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batchid'], ['batchdetails.batchid'], ),
    sa.PrimaryKeyConstraint('useid')
    )
    op.create_table('proctordetails',
    sa.Column('proctorusername', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('proctorcontact', sa.Integer(), nullable=False),
    sa.Column('batchid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batchid'], ['batchdetails.batchid'], ),
    sa.PrimaryKeyConstraint('proctorusername')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proctordetails')
    op.drop_table('candidatedetails')
    op.drop_table('usermaster')
    op.drop_table('user_detail_list')
    op.drop_table('tokenmaster')
    op.drop_table('tb_project')
    op.drop_table('tb_notification')
    op.drop_table('tb_iframe')
    op.drop_table('tb_customer')
    op.drop_table('proctor_batch_detail')
    op.drop_table('otp_table')
    op.drop_table('login_status')
    op.drop_table('enginetable')
    op.drop_table('customerusertbl')
    op.drop_table('candidateLogsTbl')
    op.drop_table('batchdetails')
    # ### end Alembic commands ###
